namespace:
  enabled: false
secret:
  enabled: false
postgres:
  enabled: false
redis:
  enabled: false
kong:
  enabled: false
auth-service:
  enabled: false
account-service:
  enabled: false
transfer-service:
  enabled: true
notification-service:
  enabled: false
frontend:
  enabled: false
ingress:
  enabled: false
