{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "banking-demo.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "banking-demo.frontend.fullname" . }}
    {{- include "banking-demo.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "banking-demo.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "banking-demo.frontend.fullname" . }}
        {{- include "banking-demo.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.frontend.securityContext.pod }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.frontend.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          {{- with .Values.frontend.securityContext.container }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
              name: {{ .Values.frontend.service.portName }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- if .Values.frontend.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.readinessProbe.path }}
              port: {{ .Values.frontend.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
            {{- if .Values.frontend.readinessProbe.timeoutSeconds }}
            timeoutSeconds: {{ .Values.frontend.readinessProbe.timeoutSeconds }}
            {{- end }}
          {{- end }}
{{- end }}
