{{- $svc := index .Values "transfer-service" }}
{{- if $svc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "banking-demo.transfer-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "banking-demo.transfer-service.fullname" . }}
    {{- include "banking-demo.transfer-service.labels" . | nindent 4 }}
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      {{- include "banking-demo.transfer-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "banking-demo.transfer-service.fullname" . }}
        {{- include "banking-demo.transfer-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with $svc.securityContext.pod }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $svc.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $svc.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: transfer-service
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          imagePullPolicy: {{ $svc.image.pullPolicy }}
          {{- with $svc.securityContext.container }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ $svc.service.port }}
              name: {{ $svc.service.portName }}
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $svc.secretRef.name }}
                  key: {{ $svc.secretRef.keys.databaseUrl }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $svc.secretRef.name }}
                  key: {{ $svc.secretRef.keys.redisUrl }}
            {{- if $svc.rabbitmqSecretRef }}
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $svc.rabbitmqSecretRef.name }}
                  key: {{ $svc.rabbitmqSecretRef.key }}
            {{- end }}
            - name: CORS_ORIGINS
              value: {{ $svc.corsOrigins | quote }}
            {{- range $k, $v := $svc.extraEnv }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- if $svc.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $svc.readinessProbe.path }}
              port: {{ $svc.readinessProbe.port }}
            initialDelaySeconds: {{ $svc.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $svc.readinessProbe.periodSeconds }}
            {{- if $svc.readinessProbe.timeoutSeconds }}
            timeoutSeconds: {{ $svc.readinessProbe.timeoutSeconds }}
            {{- end }}
          {{- end }}
{{- end }}
