apiVersion: v1
kind: Service
metadata:
  name: k8s-chatbot
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: k8s-chatbot
spec:
  selector:
    app.kubernetes.io/name: k8s-chatbot
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      name: http
